In [1]:
import cv2 as cv
import numpy as np
import pickle

In [3]:
names = [
    'sun',
    'moon',
    'mercury',
    'venus',
    'mars',
    'jupiter',
    'saturn',
    'uranus',
    'neptune',
    'pluto',
    'ceres',
    'conjunction',
    'opposition',
    'square',
    'sextile',
    'trine',
    'chart_frame_equal_house',
    'aspect_grid_frame_withceres'
]

In [5]:
images = {}
for i in names:
    path = 'images/'+i+'.jpg'
    images[i] = cv.imread(path, 0)

In [24]:
images['sun'].shape

(24, 26)

In [14]:
a_dictionary = {"a": 1}
file_to_write = open("images.pickle", "wb")
pickle.dump(images, file_to_write)

In [18]:
file_to_write.close()

In [22]:
file_to_read = open("images.pickle", "rb")
loaded_dictionary = pickle.load(file_to_read)
print(loaded_dictionary.keys())

dict_keys(['sun', 'moon', 'mercury', 'venus', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto', 'ceres', 'conjunction', 'opposition', 'square', 'sextile', 'trine', 'chart_frame_equal_house', 'aspect_grid_frame_withceres'])


In [26]:
import numpy as np 
from PIL import Image as im  
def main():
    array = np.arange(0, 737280, 1, np.uint8)
    print(type(array))
    print(array.shape)
    array = np.reshape(array, (1024, 720))      
    print(array.shape)
    print(array)
    data = im.fromarray(array) 
    print(data)
    data.save('gfg_dummy_pic.png')  
# driver code 
if __name__ == "__main__": 
    
  # function call 
  main() 

<class 'numpy.ndarray'>
(737280,)
(1024, 720)
[[  0   1   2 ... 205 206 207]
 [208 209 210 ... 157 158 159]
 [160 161 162 ... 109 110 111]
 ...
 [144 145 146 ...  93  94  95]
 [ 96  97  98 ...  45  46  47]
 [ 48  49  50 ... 253 254 255]]
<PIL.Image.Image image mode=L size=720x1024 at 0x1957F785668>
